import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  title: {
    flexDirection: 'row',
  },
  stepper: {
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  wrapInfo: {
    marginLeft: 'auto',
    marginRight: 'auto',
    width: '90%',
    borderRadius: 10,
    height: 50,
    backgroundColor: '#dfdede',
    marginTop: '4%',
  },
  selectWrapper: {
    height: 50,
    backgroundColor: '#efefef',
    borderColor: '#efefef',
    borderRadius: 10,
    borderWidth: 0,
    marginHorizontal: '5%',
  },
  buttonOrder: {
    height: 50,
    width: '90%',
    backgroundColor: '#393939',
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: '3%',
    borderRadius: 10,
  },
  textOrder: {
    color: '#ffcd61',
    fontSize: 20,
    fontWeight: '800',
    marginTop: 'auto',
    marginBottom: 'auto',
    textAlign: 'center',
  },
  buttonSee: {
    height: 50,
    width: '90%',
    backgroundColor: '#ffcd61',
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: '3%',
    borderRadius: 10,
  },
  textSee: {
    color: '#393939',
    fontSize: 20,
    fontWeight: '800',
    marginTop: 'auto',
    marginBottom: 'auto',
    textAlign: 'center',
  },
  //second payment
  imageWrapper: {
    height: 190,
    width: 320,
    borderRadius: 10,
    marginTop: '5%',
    marginBottom: '4%',
  },
  pricing: {
    flexDirection: 'row',
  },
  //third payment
  copy: {
    height: 40,
    width: '70%',
    backgroundColor: '#ffcd61',
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: '3%',
    borderRadius: 10,
  },
  textCopy: {
    color: '#393939',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 'auto',
    marginBottom: 'auto',
    textAlign: 'center',
  },
  buttonFinish: {
    height: 50,
    width: '90%',
    backgroundColor: '#ffcd61',
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: '3%',
    borderRadius: 10,
  },
  textFinish: {
    color: '#393939',
    fontSize: 20,
    fontWeight: '800',
    marginTop: 'auto',
    marginBottom: 'auto',
    textAlign: 'center',
  },
  //finish payment
  imageVehicles: {
    width: '100%',
    height: 200,
  },
  imgVehicle: {
    width: '100%',
    height: '100%',
  },
  buttonTotal: {
    height: 50,
    width: '90%',
    backgroundColor: '#ffcd61',
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: '3%',
    borderRadius: 10,
  },
  textPrice: {
    color: '#393939',
    fontSize: 20,
    fontWeight: '800',
    marginTop: 'auto',
    marginBottom: 'auto',
    textAlign: 'center',
  },
});
export default styles;
