import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  title: {
    flexDirection: 'row',
  },
  iconBack: {
    marginTop: '5%',
    marginLeft: '5%',
  },
  titlePayment: {
    fontSize: 20,
    fontWeight: '900',
    marginTop: '5%',
    paddingLeft: '6%',
  },
  stepper: {
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  wrapInfo: {
    marginLeft: 'auto',
    marginRight: 'auto',
    width: '90%',
    borderRadius: 10,
    height: 50,
    backgroundColor: '#dfdede',
    marginTop: '4%',
    borderWidth: 0,
  },
  selectWrapper: {
    height: 50,
    backgroundColor: '#efefef',
    borderColor: '#efefef',
    borderRadius: 10,
    borderWidth: 0,
    marginHorizontal: '5%',
  },
  buttonOrder: {
    height: 50,
    width: '90%',
    backgroundColor: '#393939',
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: '3%',
    borderRadius: 10,
  },
  textOrder: {
    color: '#ffcd61',
    fontSize: 20,
    fontWeight: '800',
    marginTop: 'auto',
    marginBottom: 'auto',
    textAlign: 'center',
  },
  buttonSee: {
    height: 50,
    width: '90%',
    backgroundColor: '#ffcd61',
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: '3%',
    borderRadius: 10,
    marginBottom: '10%',
  },
  textSee: {
    color: '#393939',
    fontSize: 20,
    fontWeight: '800',
    marginTop: 'auto',
    marginBottom: 'auto',
    textAlign: 'center',
  },
  cardNumber: {
    borderWidth: 0,
    borderRadius: 10,
    fontSize: 17,
  },
  iconInfo: {
    marginLeft: 'auto',
    marginRight: '5%',
    width: 30,
    height: 30,
    resizeMode: 'cover',
    marginTop: '10%',
  },
  priceVehicle: {
    marginTop: '10%',
    fontSize: 24,
    marginLeft: '5%',
  },
  info: {
    marginLeft: '5%',
    marginTop: '2%',
    fontSize: 16,
  },
  //second payment
  imageWrapper: {
    height: 190,
    width: 360,
    borderRadius: 10,
    marginTop: '5%',
    marginBottom: '4%',
  },
  imageVehicle: {
    width: '100%',
    height: 190,
  },
  pricing: {
    flexDirection: 'row',
    marginTop: '2%',
  },
  codePayment: {
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 15,
  },
  codeText: {
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 24,
    marginTop: '1%',
  },
  infoCode: {
    marginRight: '2%',
    marginLeft: '2%',
    textAlign: 'center',
    fontSize: 13,
    marginTop: '1%',
  },
  timer: {
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 18,
    color: '#e60728',
    marginTop: '1%',
  },
  infoBank: {
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 14,
    marginTop: '1%',
  },
  bankCode: {
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 20,
    marginTop: '1%',
  },
  brand: {
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 16,
    marginTop: '1%',
  },
  useBooking: {
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 12,
    marginTop: '1%',
  },
  iconInfoo: {
    marginLeft: 'auto',
    marginRight: '5%',
    width: 30,
    height: 30,
    resizeMode: 'cover',
    // marginTop: '10%',
  },
  //third payment
  copy: {
    height: 40,
    width: '70%',
    backgroundColor: '#ffcd61',
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: '3%',
    borderRadius: 10,
  },
  textCopy: {
    color: '#393939',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 'auto',
    marginBottom: 'auto',
    textAlign: 'center',
  },
  buttonFinish: {
    height: 50,
    width: '90%',
    backgroundColor: '#ffcd61',
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: '3%',
    borderRadius: 10,
    marginBottom: '10%',
  },
  textFinish: {
    color: '#393939',
    fontSize: 20,
    fontWeight: '800',
    marginTop: 'auto',
    marginBottom: 'auto',
    textAlign: 'center',
  },
  //finish payment
  imageVehicles: {
    width: '100%',
    height: 200,
  },
  imgVehicle: {
    width: '100%',
    height: '100%',
  },
  buttonTotal: {
    height: 50,
    width: '90%',
    backgroundColor: '#ffcd61',
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: '3%',
    borderRadius: 10,
  },
  textPrice: {
    color: '#393939',
    fontSize: 20,
    fontWeight: '800',
    marginTop: 'auto',
    marginBottom: 'auto',
    textAlign: 'center',
  },
  successPayment: {
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: '5%',
    marginBottom: '5%',
    fontSize: 20,
    color: '#0c7829',
  },
});
export default styles;
