import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  imageProfile: {
    // position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: 50,
    // backgroundColor: '#000',
    resizeMode: 'cover',
  },
  imageWrapper: {
    // marginRight: 'auto',
    // marginLeft: 'auto',
    paddingTop: 10,
    flexDirection: 'row',
    backgroundColor: '#FFF',
    shadowColor: '#000',
    shadowOffset: {width: 1, height: 1},
    shadowOpacity: 0.4,
    shadowRadius: 3,
    elevation: 5,
    paddingBottom: 10,
  },
  nameUser: {
    fontSize: 24,
    marginBottom: 'auto',
    marginTop: 'auto',
    marginLeft: 5,
  },
  btnEdit: {
    flexDirection: 'row',
    marginVertical: '4%',
    marginLeft: '5%',
  },
  arrowIcon: {
    marginLeft: 'auto',
    marginRight: '5%',
    width: 20,
    height: 20,
    resizeMode: 'cover',
  },
  menu: {
    fontWeight: '500',
    fontSize: 18,
    color: '#393939',
    // marginTop: '4%',
    // marginLeft: '5%',
    flex: 1,
  },
  btnLgt: {
    alignItems: 'center',
    backgroundColor: '#FFCD61',
    padding: 10,
    borderRadius: 15,
    height: 50,
    textAlign: 'center',
    marginTop: '50%',
    marginBottom: '5%',
  },
  logout: {
    color: '#000000',
    fontWeight: 'bold',
    fontSize: 18,
    marginBottom: 'auto',
    marginTop: 'auto',
  },
  //update profile
  title: {
    flexDirection: 'row',
    marginBottom: '5%',
  },
  imageUpdate: {
    flexDirection: 'row',
    backgroundColor: '#000',
  },
  buttonTake: {
    color: '#FFF',
    backgroundColor: '#393939',
    height: 40,
    borderRadius: 10,
    width: '100%',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  textTake: {
    textAlign: 'center',
    fontSize: 12,
    marginBottom: 'auto',
    marginTop: 'auto',
    fontWeight: '900',
    color: '#ffcd61',
  },
  buttonBrowse: {
    marginTop: '5%',
    color: '#FFF',
    backgroundColor: '#ffcd61',
    height: 40,
    borderRadius: 10,
    width: '100%',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  textBrowse: {
    textAlign: 'center',
    fontSize: 12,
    marginBottom: 'auto',
    marginTop: 'auto',
    fontWeight: '900',
  },
  iconButton: {
    marginLeft: '5%',
    marginTop: '5%',
  },
  titleUpdate: {
    marginTop: '5%',
    marginLeft: '5%',
    fontSize: 17,
  },
  radioButtonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 45,
  },
  radioButton: {
    height: 20,
    width: 20,
    backgroundColor: '#F8F8F8',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E6E6E6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioButtonIcon: {
    height: 14,
    width: 14,
    borderRadius: 7,
    backgroundColor: '#98CFB6',
  },
  radioButtonText: {
    fontSize: 16,
    marginLeft: 16,
  },
  buttonRadio: {
    flexDirection: 'row',
    // backgroundColor: 'red',
  },
  radioCheck: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '50%',
    // backgroundColor: 'blue',
  },
  modal: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  content: {
    backgroundColor: '#fff',
    height: 180,
    width: 325,
    borderRadius: 12,
  },
  modalTxt: {
    color: '#000',
    textAlign: 'center',
    paddingTop: '5%',
    fontSize: 20,
  },
  modalBtn: {
    width: '40%',
    height: '60%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
  },
});

export default styles;
